version: '2.1'
services:
  base:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/server
    environment:
      - DOTENV_PATH=.env
  server-development:
      extends: base
      command: yarn start-live
      environment:
        - NODE_ENV=development
      ports:
        - 4000:3000
      links:
          - database
  server-test:
      extends: base
      command: yarn start-live
      environment:
        - NODE_ENV=test
      ports:
        - 4000:3000
      links:
          - database
  database:
    image: postgres:9.6.5-alpine
    ports:
      - 5432:5432
    volumes:
      - supernova-database:/var/lib/postgresql/data
volumes:
  supernova-database:
