version: '2.1'
services:
  base:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DOTENV_PATH=.env
  server:
      extends: base
      command: yarn start-live
      environment:
        - NODE_ENV=test
      ports:
        - 4000:4000
        - 9229:9229
      links:
          - database
      volumes:
        - ./src:/server/src
        - ./test:/server/test
  database:
    image: postgres:9.6.5-alpine
    ports:
      - 5432:5432
    volumes:
      - supernova-database:/var/lib/postgresql/data
volumes:
  supernova-database:
