version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
     - image: circleci/node:10.9-stretch-browsers
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true
      - run:
          name: Build and start database
          command: docker-compose up -d --build database
      - run:
          name: Build server
          command: docker-compose build server
      - run:
          name: Run migrations
          command: make run-test-migration
      - run:
          name: Run seeds
          command: make run-seeds
      - run:
          name: Run tests
          command: make test